version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aditya
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
